import {mkdir, writeFile, cp, rm, readFile} from 'node:fs/promises';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {icons} from './icons.mjs';
import {areaHub, areaLinks, localGuides} from './local-content.mjs';
import {breadcrumbHTML, structuredData} from './seo.mjs';
import {componentGuides, componentLinks} from './component-content.mjs';
import {secondaryAreas} from './secondary-areas.mjs';
import {richCoverage, richReviews} from './rich-components.mjs';
import {additionalServices} from './additional-services.mjs';
import {chatMarkup} from './chat-markup.mjs';
import {googleProfile} from './google-profile.mjs';
const root = dirname(dirname(fileURLToPath(import.meta.url)));
const imageDimensions=JSON.parse(await readFile(join(root,'asset-dimensions.json'),'utf8'));
const correctImageDimensions=(html)=>html.replace(/<img\b[^>]+>/g,tag=>{const name=tag.match(/src="\/assets\/images\/([^\"]+)"/)?.[1];const image=imageDimensions[name];const variants=Object.values(responsiveImages).find(item=>item.default===name)?.variants;const srcset=variants?.map(v=>`/assets/images/${v.name} ${v.width}w`).join(', ');if(srcset){tag=tag.replace(/\s(?:srcset|sizes)="[^"]*"/g,'');tag=tag.replace('>',` srcset="${srcset}" sizes="${(tag.includes('home-hero-image')||tag.includes('inner-hero-image'))?'100vw':'(max-width: 760px) 100vw, 50vw'}">`);}if(image)tag=tag.replace(/width="\d+"/,`width="${image.width}"`).replace(/height="\d+"/,`height="${image.height}"`);if(variants){const avif=variants.map(v=>`/assets/images/${v.avif} ${v.width}w`).join(", ");const sizes=tag.match(/sizes="([^\"]+)"/)?.[1]||"100vw";const source=`<source type="image/avif" srcset="${avif}" sizes="${sizes}">`;return tag.includes("hero-image")?source+tag:`<picture class="responsive-picture">${source}${tag}</picture>`;}return tag;});
const origin='https://hireyardu.com';
const phone='(919) 592-8328';
const towns=['Raleigh','Cary','Apex','Wake Forest','Fuquay-Varina','Holly Springs'];
const responsiveImages=JSON.parse(await readFile(join(root,'responsive-images.json'),'utf8'));
const img=(name)=>`/assets/images/${name==='yardu-logo.svg'?'yardu-logo-centered.svg':responsiveImages[name]?.default||name}`;
const links=[['/','Home'],['/services-2/','Services'],['/our-mission/','Mission'],['/projects/','Projects'],['/reviews/','Reviews'],['/service-areas/','Service Area']];
const serviceNav=[{slug:'lawn-maintenance',name:'The YardU Special',short:'The complete core lawn care package.'},...componentGuides.map(g=>({slug:g.slug,name:g.name,short:'Part of the YardU Special.'})),...additionalServices.map(g=>({...g,name:g.nav}))];
const serviceMenu=(mobile=false)=>`<details class="${mobile?'':'nav-dropdown service-disclosure'}"><summary>Services <span aria-hidden="true">${mobile?'+':'⌄'}</span></summary><div class="${mobile?'':'services-menu'}"><a href="/services-2/"><span>All services</span><small>Find the right scope for your property.</small></a>${serviceNav.map(g=>`<a href="/services/${g.slug}/"><span>${g.name}</span><small>${g.short}</small></a>`).join('')}</div></details>`;
const nav=(path,mobile=false)=>links.map(([href,label])=>href==='/services-2/'?serviceMenu(mobile):`<a href="${href}"${href===path?' aria-current="page"':''}>${label}</a>`).join('');
const estimate=(label='Request a free estimate')=>`<a class="button button-primary" href="/getestimate/"><span>${label}</span><span class="button-icon">${icons.arrow}</span></a>`;
const call=()=>`<a class="button button-outline-dark" href="tel:+19195928328"><span>Call ${phone}</span>${icons.phone}</a>`;
const heading=(eyebrow,title,copy='')=>`<div class="section-heading"><p class="eyebrow">${eyebrow}</p><h2>${title}</h2>${copy?`<p>${copy}</p>`:''}</div>`;
const header=(path)=>`<a class="skip-link" href="#main-content">Skip to content</a><div class="topbar" role="complementary" aria-label="YardU contact information"><div class="shell topbar-inner"><span>Landscaping with a Purpose · North Carolina</span><a href="tel:+19195928328">${icons.phone}${phone}</a></div></div><div class="header-sentinel"></div><header class="site-header" data-site-header><div class="shell nav-shell"><a class="brand" href="/" aria-label="YardU home"><img src="${img('yardu-logo.svg')}" alt="YardU — Landscaping with a Purpose" width="500" height="500"></a><nav class="desktop-nav" aria-label="Primary navigation">${nav(path)}</nav><div class="nav-actions">${estimate('Request estimate')}<button class="menu-toggle" type="button" aria-label="Open menu" aria-expanded="false" aria-controls="mobile-menu">${icons.menu}</button></div></div></header><div class="menu-scrim" data-menu-scrim hidden></div><aside class="mobile-menu" id="mobile-menu" aria-label="Mobile navigation" hidden><div class="mobile-menu-top"><img src="${img('yardu-logo.svg')}" alt="YardU" width="90" height="90"><button class="menu-close" aria-label="Close menu">${icons.close}</button></div><div class="mobile-menu-actions">${estimate()}${call()}</div><nav aria-label="Mobile navigation links">${nav(path,true)}</nav><p>Landscaping with a Purpose</p></aside>`;
const footer=()=>`<footer class="site-footer"><div class="shell footer-grid"><div class="footer-brand"><img src="${img('yardu-logo.svg')}" alt="YardU" width="500" height="500"><p>Training tomorrow’s youth, one yard at a time.</p><a class="text-link" href="https://www.instagram.com/theyarduniversity/" target="_blank" rel="noopener">${icons.instagram} Follow YardU</a></div><div><h2>Services</h2><ul><li><a href="/services/lawn-maintenance/">The YardU Special</a></li>${additionalServices.map(g=>`<li><a href="/services/${g.slug}/">${g.nav}</a></li>`).join('')}<li><a href="/services-2/">All services</a></li><li><a href="/getestimate/">Request an estimate</a></li></ul></div><div><h2>Company</h2><ul>${links.slice(2).map(([href,l])=>`<li><a href="${href}">${l}</a></li>`).join('')}<li><a href="https://hireyardu.com/meet-the-founders/">Meet the founders</a></li><li><a href="https://hireyardu.com/watch-yardu-video/">Watch YardU’s video</a></li><li><a href="https://hireyardu.com/franchising/">Franchising</a></li></ul></div><div><h2>Contact</h2><ul><li><a href="tel:+19195928328">${phone}</a></li><li>Serving Raleigh, Cary, Apex, Wake Forest, Fuquay-Varina &amp; Holly Springs, NC.</li><li><a href="https://www.linkedin.com/company/yardu">LinkedIn</a></li></ul></div></div><div class="shell footer-bottom"><p>© 2026 YardU. All rights reserved.</p><div><a href="https://hireyardu.com/privacy-policy/">Privacy</a><a href="https://hireyardu.com/terms-conditions/">Terms</a><a href="/sitemap.xml">Sitemap</a></div></div></footer>`;
const parts=[['Mowing','mowing.png','Grass cut to suit your turf, with an even finish.','Striped lawn pictured on YardU’s current website'],['Edging','edging.png','Clean lines along sidewalks, driveways, and landscape beds.','Defined landscape bed pictured on YardU’s current website'],['Trimming','trimming-preview.jpg','Grass and weeds around fences, obstacles, and hard-to-reach corners.','YardU crew member trimming grass'],['Blowing off surfaces','property-lawn-preview.jpg','Grass clippings and debris cleared from the finished surfaces.','Lawn pictured on YardU’s current website']];
const cards=()=>`<div class="service-grid home-service-grid">${parts.map(([title,image,copy,alt],i)=>`<a class="service-card" href="/services/${['mowing','edging','trimming','blowing'][i]}/"><img src="${img(image)}" alt="${alt}" width="900" height="1100" loading="lazy"><div class="service-card-shade"></div><div class="service-card-copy"><span>0${i+1}</span><h3>${title}</h3><p>${copy}</p><span class="service-card-link">Included in the YardU Special ${icons.arrow}</span></div></a>`).join('')}</div>`;
const intro=()=>`<section class="intro section-pad"><div class="shell intro-grid"><div class="intro-copy">${heading('More than lawn care','A better yard.<br>A brighter future.','YardU began with student-athletes at NC State. Now, the same lessons in hard work, discipline, and responsibility help young people prepare for what comes next.')}<div class="intro-points"><div><span>01</span><p>Real work. Real life skills.</p></div><div><span>02</span><p>Responsibility, communication, and professionalism</p></div><div><span>03</span><p>Training tomorrow’s youth, one yard at a time</p></div></div><a class="text-link" href="/our-mission/">Meet the mission ${icons.arrow}</a></div><div class="intro-visual"><div class="image-shell"><img src="${img('founders.jpg')}" alt="Thayer Thomas and Jackson DeSilva discussing YardU" width="1920" height="1080" loading="lazy"></div><div class="intro-badge"><strong>Purpose</strong><span>in every yard</span></div></div></div></section>`;
const services=()=>`<section class="services home-services section-pad" id="services"><div class="shell home-services-intro"><div class="home-services-copy"><p class="eyebrow eyebrow-light">The YardU Special</p><h2>Four details.<br>One cared-for lawn.</h2><span class="lime-rule" aria-hidden="true"></span><p>YardU’s core lawn mowing package brings mowing, edging, weed whacking and trimming, and blowing off surfaces together. Start here for a clean, considered finish.</p><div class="button-row">${estimate()}<a class="button button-ghost-light" href="/services/lawn-maintenance/">Explore the package ${icons.arrow}</a></div></div><div class="home-services-truck"><img src="${img('trimming-preview.jpg')}" alt="YardU crew member working along a lawn edge" width="1200" height="900" loading="lazy"></div></div><div class="shell">${cards()}</div></section>`;
const process=()=>`<section class="process section-pad"><div class="shell process-grid"><div class="process-visual"><img src="${img('trimming-preview.jpg')}" alt="YardU lawn care in progress" width="1200" height="900" loading="lazy"><div class="process-caption"><span>Start with your yard.</span><strong>Make room for your life.</strong></div></div><div class="process-copy">${heading('A clear starting point','Let’s talk about your yard.','A few details help YardU understand what you need.')}<div class="accordion process-accordion" data-accordion>${[['Tell us about the property','Share the location, lawn condition, access, and the areas you would like cared for.'],['Discuss the right scope','Ask about the core package and describe any additional work so the team can confirm what is available.'],['Confirm your estimate','Discuss price, timing, and service details directly with YardU before booking.']].map(([t,c],i)=>`<details${i===0?' open':''}><summary><span>0${i+1}</span><strong>${t}</strong>${icons.plus}</summary><div><p>${c}</p></div></details>`).join('')}</div></div></div></section>`;
const coverage=()=>richCoverage(estimate);
const testimonials=()=>richReviews();
const galleryImages=[['lawn-stripes.jpeg','Striped lawn pictured by YardU'],['trimming-preview.jpg','YardU crew member trimming a lawn'],['mulch.png','Mulch installation pictured by YardU'],['backyard.jpeg','Backyard lawn pictured by YardU'],['patio.png','Paver patio pictured on YardU’s website'],['outdoor-living.png','Outdoor living area pictured on YardU’s website']];
const gallery=()=>`<section class="gallery-preview section-pad"><div class="shell gallery-heading-row">${heading('The YardU view','The details show in the finish.','A closer look at lawns, landscape beds, and outdoor spaces.')}<a class="text-link text-link-light" href="/projects/">View the full gallery ${icons.arrow}</a></div><div class="gallery-collage shell">${galleryImages.map(([src,alt],i)=>`<figure class="gallery-item gallery-item-${i+1}"><img src="${img(src)}" alt="${alt}" loading="lazy" width="1000" height="1200"></figure>`).join('')}</div></section>`;
const additionalSection=()=>`<section class="services section-pad additional-services"><div class="shell">${heading('Beyond the core package','More ways to care for your property.','Refresh your landscape beds, clear accumulated leaves, shape an outdoor space, or bring a cleaner finish to your property.')}<div class="service-grid">${additionalServices.map((g,i)=>`<a class="service-card" href="/services/${g.slug}/"><img src="${img(g.image)}" alt="${g.image==='property-lawn-preview.jpg'?'Residential lawn pictured on YardU’s website':g.image==='backyard.jpeg'?'Backyard pictured on YardU’s website':g.name+' imagery published by YardU'}" width="900" height="1100" loading="lazy"><div class="service-card-shade"></div><div class="service-card-copy"><span>0${i+1}</span><h3>${g.nav}</h3><p>${g.short}</p><span class="service-card-link">Explore the service ${icons.arrow}</span></div></a>`).join('')}</div></div></section>`;
const faqs=[['What is included in the YardU Special?','The core package includes mowing, edging, weed whacking and trimming, and blowing off surfaces. YardU’s published service description also includes light shaping of low hedges and shrubs as part of the regular mowing cycle. Confirm your property’s scope with the team.'],['Where does YardU work?',`The current YardU site lists ${towns.slice(0,-1).join(', ')}, and ${towns.at(-1)}, North Carolina. Confirm your exact property when requesting an estimate.`],['What does “Landscaping with a Purpose” mean?','YardU creates opportunities for young people to learn work ethic, communication, professionalism, and responsibility through real work.'],['How do I request an estimate?',`Call ${phone} to discuss your property. The form in this local preview demonstrates the request flow; it does not send a lead.`]];
const faq=()=>`<section class="faq-section section-pad"><div class="shell faq-grid"><div>${heading('Straight answers','Questions before you book?','Start with the details that matter to your property.')}<a class="text-link" href="/getestimate/">Talk to YardU ${icons.arrow}</a></div><div class="accordion faq-accordion" data-accordion>${faqs.map(([q,a],i)=>`<details${i===0?' open':''}><summary><strong>${q}</strong>${icons.plus}</summary><div><p>${a}</p></div></details>`).join('')}</div></div></section>`;
const form=()=>`<section class="contact-section section-pad" id="estimate"><div class="shell contact-grid"><div class="contact-copy"><p class="eyebrow eyebrow-light">Start with your property</p><h2>Your lawn.<br>Our purpose.</h2><p>Tell YardU what your lawn needs. A conversation is the first step toward the right scope and estimate.</p><div class="contact-direct"><a class="contact-phone" href="tel:+19195928328">${icons.phone}<span><small>Prefer to call?</small><strong>${phone}</strong></span></a></div><p class="preview-note">Local preview: the form is disconnected. Call YardU for a live request. Nothing entered here is saved or sent.</p></div><div class="yardu-form-card"><p class="eyebrow">Request an estimate</p><h3>Tell us about your yard.</h3><form id="estimate-form" novalidate><div class="form-grid"><div><label for="name">Full name</label><input id="name" name="name" autocomplete="name" required minlength="2" aria-describedby="name-error"><small class="field-error" id="name-error"></small></div><div><label for="phone">Phone</label><input id="phone" name="phone" type="tel" autocomplete="tel" required aria-describedby="phone-error"><small class="field-error" id="phone-error"></small></div><div class="form-wide"><label for="email">Email</label><input id="email" name="email" type="email" autocomplete="email" required aria-describedby="email-error"><small class="field-error" id="email-error"></small></div><div><label for="city">Property city</label><input id="city" name="city" autocomplete="address-level2" required aria-describedby="city-error"><small class="field-error" id="city-error"></small></div><div><label for="service">What do you need?</label><select id="service" name="service" required aria-describedby="service-error"><option value="">Select an option</option><option>The YardU Special</option>${additionalServices.map(g=>`<option>${g.name}</option>`).join('')}<option>Discuss other property needs</option></select><small class="field-error" id="service-error"></small></div><div class="form-wide"><label for="details">Property details <span>(optional)</span></label><textarea id="details" name="details" rows="3" maxlength="2000" placeholder="Lawn condition, access, and any questions"></textarea></div></div><button class="button button-primary" type="submit"><span>Preview estimate request</span>${icons.arrow}</button><p id="form-status" role="status" tabindex="-1"></p><noscript><p>The preview form needs JavaScript to validate. Nothing can be sent. Call YardU to request an estimate.</p></noscript></form></div></div></section>`;
const trust=()=>`<section class="trust-rail shell" aria-label="Why YardU"><a class="trust-card" href="/our-mission/"><strong class="trust-display">Purpose</strong><h2>More than lawn care</h2><p>Teaching tomorrow’s youth through real work.</p><span class="text-link">Our mission ${icons.arrow}</span></a><a class="trust-card" href="/services/lawn-maintenance/"><strong class="trust-display">4 details</strong><h2>The YardU Special</h2><p>Mowing, edging, trimming, and blowing off surfaces.</p><span class="text-link">The core package ${icons.arrow}</span></a><a class="trust-card" href="/service-areas/"><strong class="trust-display">Local</strong><h2>North Carolina roots</h2><p>Serving six communities listed on YardU’s website.</p><span class="text-link">Service area ${icons.arrow}</span></a><a class="trust-card" href="/getestimate/"><strong class="trust-display">Let’s talk</strong><h2>Your yard comes first</h2><p>Discuss your property, service needs, and timing.</p><span class="text-link">Get an estimate ${icons.arrow}</span></a></section>`;
const homeHero=()=>`<section class="home-hero home-hero-truck"><picture class="home-hero-visual"><img class="home-hero-image" src="${img('property-lawn-preview.jpg')}" srcset="${img('property-lawn-480.jpg')} 480w, ${img('property-lawn-800.jpg')} 800w, ${img('property-lawn-preview.jpg')} 1200w" sizes="100vw" loading="eager" decoding="async" alt="Residential lawn pictured on YardU’s website" width="1800" height="1350" fetchpriority="high"></picture><div class="home-hero-shade"></div><div class="home-hero-brand"><img src="${img('yardu-logo.svg')}" alt="YardU" width="500" height="500"></div><div class="shell home-hero-content"><a class="hero-google" href="${googleProfile.googleReviewsUrl}" target="_blank" rel="noopener">${icons.google}<span>Read our Google reviews</span>${icons.arrow}</a><p class="eyebrow eyebrow-light">Lawn care in Raleigh &amp; the Triangle</p><h1 class="liquid-title"><span>Lawn care</span><span>in Raleigh</span><span>&amp; the Triangle</span></h1><p class="hero-copy">A well-kept yard today. Life skills for tomorrow. YardU brings mowing and lawn care to Raleigh and the Triangle.</p><div class="hero-action-wrap"><div class="button-row">${estimate()}<a class="button button-ghost-light" href="#services">Explore our services ${icons.arrow}</a></div><a class="hero-phone-link" href="tel:+19195928328">${icons.phone}<span>Prefer to talk? <strong>${phone}</strong></span></a></div></div></section>`;
const inner=(eyebrow,title,copy,image='property-lawn-preview.jpg')=>`<section class="inner-hero"><picture class="inner-hero-visual"><img class="inner-hero-image" src="${img(image)}" width="1200" height="1600" alt="Landscape pictured on YardU’s website" loading="eager" fetchpriority="high" decoding="async"></picture><div class="shell inner-hero-content"><p class="eyebrow eyebrow-light">${eyebrow}</p><h1>${title}</h1><p>${copy}</p><div class="button-row">${estimate()}</div></div></section>`;
const cta=()=>`<section class="simple-cta section-pad"><div class="shell simple-cta-inner"><div><p class="eyebrow eyebrow-light">Your yard is next</p><h2>Care for your lawn.<br>Invest in tomorrow.</h2></div>${estimate()}</div></section>`;
const pages=[
{path:'/',title:'Lawn Care in Raleigh & the Triangle | YardU',description:'YardU’s core lawn care package includes mowing, edging, trimming, and blowing off surfaces. Serving Raleigh, Cary, and neighboring NC communities.',body:homeHero()+trust()+intro()+services()+additionalSection()+process()+testimonials()+gallery()+coverage()+faq()+form(),class:'home-page'},
{path:'/services-2/',title:'Lawn & Landscaping Services | YardU',description:'Explore the YardU Special lawn package plus mulch, straw and rock, leaf and debris removal, hardscaping, and pressure washing.',body:inner('Our services','Lawn &amp; landscaping<br>services in Raleigh.','Explore the core lawn package and additional property services.')+services()+additionalSection()+process()+faq()+cta()},
{path:'/services/lawn-maintenance/',title:'The YardU Special Lawn Mowing Package | YardU',description:'Four lawn care details in one core package: mowing, edging, trimming, and blowing off surfaces. Discuss your property with YardU.',body:inner('Lawn mowing & maintenance','Lawn mowing &amp;<br>maintenance in Raleigh.','Meet the four parts of the YardU Special.')+`<section class="section-pad"><div class="shell">${heading('What’s included','From the first cut to the final cleanup.')}<div class="yardu-service-details">${parts.map(([t,i,c,a],n)=>`<article id="${['mowing','edging','trimming','blowing'][n]}"><img src="${img(i)}" alt="${a}" loading="lazy" width="900" height="900"><div><p class="eyebrow">0${n+1} · The YardU Special</p><h2>${t}</h2><p>${c}</p><a class="text-link" href="/services/${['mowing','edging','trimming','blowing'][n]}/">Explore this component →</a>${n===2?'<p>YardU’s published package includes light shaping of low hedges and shrubs as part of the regular mowing cycle. Discuss the scope for your property.</p>':''}</div></article>`).join('')}</div></div></section>`+`<section class="section-pad"><div class="shell local-content"><h2>Lawn care for your community</h2><p>Discuss your address and property needs with YardU. Read the local guides for useful preparation questions and resources.</p>${areaLinks}<p>YardU also lists Apex, Wake Forest, Fuquay-Varina, and Holly Springs. Use the <a href="/service-areas/">service area hub</a> to confirm your property's fit.</p><h2>Agree on the scope before booking</h2><p>Share the grass condition, access, fenced sections, edges, and surfaces to clear. Confirm the visit frequency, timing, and price directly with YardU. Work outside this package should be discussed separately.</p></div></section>`+process()+faq()+cta()},
{path:'/our-mission/',title:'Our Mission | YardU Landscaping with a Purpose',description:'YardU gives young people opportunities to develop work ethic, communication, professionalism, and responsibility through lawn care.',body:inner('Our mission','A yard today.<br>A future tomorrow.','Training tomorrow’s youth, one yard at a time.','founders.jpg')+intro()+`<section class="section-pad"><div class="shell mission-story">${heading('Built from experience','Work ethic is learned by doing.')}<p>As student-athletes at NC State, YardU’s founders learned the value of hard work, discipline, and resilience. Jackson DeSilva and Thayer Thomas brought those lessons into a business with a purpose: giving young people a place to work, learn, and prepare for the future.</p><blockquote>“It’s more than just lawn care. It’s about building a workforce, teaching responsibility, and shaping the leaders of tomorrow.”<cite>Jackson DeSilva · Co-Founder</cite></blockquote><p>Each yard is an opportunity to practice responsibility, communication, and professionalism. Your lawn care becomes part of something bigger.</p></div></section>`+testimonials()+cta()},
{path:'/projects/',title:'Lawn Care Gallery | YardU',description:'Explore lawn care, landscape beds, and outdoor-space imagery from YardU.',body:inner('The YardU view','The details make<br>the difference.','Explore lawns, landscape beds, and outdoor spaces from YardU.')+gallery()+cta()},
{path:'/service-areas/',title:'Service Areas | YardU in Raleigh, Cary & Nearby Communities',description:'YardU lists Raleigh, Cary, Apex, Wake Forest, Fuquay-Varina, and Holly Springs, NC. Confirm your exact property and availability with the team.',body:inner('North Carolina communities','Close to home.<br>Built on purpose.','Find your community and discuss your property with YardU.')+coverage()+areaHub+faq()+cta()},
{path:'/getestimate/',title:'Request an Estimate | YardU',description:'Discuss your lawn care needs with YardU at (919) 592-8328. This local preview form does not send or save a lead.',body:inner('Let’s start with your yard','Tell us what<br>you have in mind.','A clear scope starts with a conversation.')+form()+process()},
{path:'/404/',title:'Page Not Found | YardU',description:'Find your way back to YardU lawn care.',body:inner('404','Let’s get back<br>to your yard.','This page could not be found.')+`<section class="section-pad"><div class="shell"><a class="button button-primary" href="/">Back to home ${icons.arrow}</a></div></section>`}
];
for(const guide of [...localGuides,...secondaryAreas])pages.push({...guide,body:inner(`${guide.city}, North Carolina`,`Lawn care in<br>${guide.city}.`,guide.intro)+`<section class="section-pad"><div class="shell local-content">${guide.content}<h2>Explore the package and nearby communities</h2><p><a href="/services/lawn-maintenance/">The YardU Special</a> brings its four core components together.</p>${componentLinks()}<h2>Work beyond the regular lawn package</h2><p>Explore <a href="/services/mulch-straw-rock/">mulch, straw, and rock installation</a>, <a href="/services/leaf-debris-removal/">leaf and debris removal</a>, <a href="/services/hardscaping/">hardscaping</a>, and <a href="/services/pressure-washing/">pressure washing</a>. Discuss the property, separate scope, and current availability with the team.</p>${areaLinks}</div></section>`+cta()});
for(const guide of componentGuides)pages.push({path:`/services/${guide.slug}/`,title:`${guide.name} | Part of the YardU Special Lawn Package`,description:guide.intro+' Explore scope, property questions, and the other parts of the package.',component:guide.name,body:inner('Part of the YardU Special',guide.name+'<br>in Raleigh &amp; the Triangle.',guide.intro,guide.image)+`<section class="section-pad"><div class="shell local-content">${guide.content}<h2>One package, four connected details</h2><p>Return to <a href="/services/lawn-maintenance/">the complete YardU Special</a> or explore the other components.</p>${componentLinks(guide.slug)}<h2>Find your area</h2><p>Use the local guides to prepare your property request and confirm address-level availability.</p>${areaLinks}</div></section>`+cta()});
pages.push({path:'/reviews/',title:'YardU Testimonials | Landscaping with a Purpose',description:'Read customer and community testimonials shared by YardU.',body:inner('YardU stories','Purpose people<br>can get behind.','The mission means more when you hear from the community.')+testimonials()+cta()});
for(const g of additionalServices)pages.push({path:`/services/${g.slug}/`,title:`${g.name} in Raleigh & the Triangle | YardU`,description:g.intro+' Discuss the scope, property, and estimate directly with YardU.',component:g.name,service:true,body:inner('YardU additional services',g.name+'<br>in Raleigh &amp; the Triangle.',g.intro,g.image)+`<section class="section-pad"><div class="shell local-content">${g.content}<h2>Explore related work</h2><p>Compare the <a href="/services-2/">complete service hub</a> and <a href="/services/lawn-maintenance/">the core lawn package</a>.</p><div class="coverage-links">${additionalServices.filter(other=>other.slug!==g.slug).map(other=>`<a href="/services/${other.slug}/">${other.nav}</a>`).join('')}</div><h2>Your community</h2>${areaLinks}</div></section>`+cta()});
const shell=(p)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${p.title.replaceAll('&','&amp;')}</title><meta name="description" content="${p.description.replaceAll('&','&amp;')}"><meta name="robots" content="noindex,nofollow"><link rel="canonical" href="${origin}${p.path}"><link rel="icon" href="${img('yardu-logo.svg')}" type="image/svg+xml"><meta property="og:title" content="${p.title.replaceAll('&','&amp;')}"><meta property="og:description" content="${p.description.replaceAll('&','&amp;')}"><meta property="og:url" content="${origin}${p.path}"><link rel="preload" href="/assets/fonts/manrope-latin.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/assets/fonts/outfit-latin.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/fonts.css"><link rel="stylesheet" href="/assets/template.css"><link rel="stylesheet" href="/assets/yardu.css"><link rel="stylesheet" href="/assets/yardu-chat.css"><meta property="og:type" content="website"><meta property="og:site_name" content="YardU"><meta property="og:image" content="${origin}${img('property-lawn-preview.jpg')}"><meta property="og:image:alt" content="YardU lawn care imagery">${p.path==='/404/'?'':structuredData(p)}<script src="/assets/site.js" defer></script><script src="/assets/yardu-chat.js" type="module"></script><script type="module" src="/assets/area-map.js"></script></head><body class="${p.class||'inner-page'}">${header(p.path)}<main id="main-content">${p.body.startsWith('<section class="inner-hero"')?p.body.replace('</section>',`</section>${breadcrumbHTML(p)}`):p.body}</main>${footer()}${chatMarkup()}<div class="mobile-cta-bar" role="navigation" aria-label="Quick contact"><a href="tel:+19195928328">${icons.phone}Call YardU</a><a href="/getestimate/">Request estimate ${icons.arrow}</a></div></body></html>`;
const dist=join(root,'dist');await rm(dist,{recursive:true,force:true});await mkdir(dist,{recursive:true});await cp(join(root,'assets'),join(dist,'assets'),{recursive:true});
for(const file of ['template.css','yardu.css','yardu-chat.css']){const path=join(dist,'assets',file);const css=await readFile(path,'utf8');await writeFile(path,css.replace(/\/\*[\s\S]*?\*\//g,'').replace(/\n[ \t]*/g,' ').replace(/[ \t]{2,}/g,' ').trim());}
for(const p of pages){const file=p.path==='/'?'index.html':p.path==='/404/'?'404.html':`${p.path.slice(1)}index.html`;await mkdir(dirname(join(dist,file)),{recursive:true});await writeFile(join(dist,file),correctImageDimensions(shell(p)));}
await writeFile(join(dist,'sitemap-candidate.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.filter(p=>p.path!='/404/').map(p=>`<url><loc>${origin}${p.path}</loc></url>`).join('')}</urlset>`);
await writeFile(join(dist,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>');
await writeFile(join(dist,'robots.txt'),'User-agent: *\nDisallow: /\n');
await writeFile(join(root,'route-manifest.json'),JSON.stringify({mode:'local-review-only',origin,routes:pages.map(p=>({path:p.path,title:p.title,description:p.description,canonical:origin+p.path,indexable:false,type:p.path==='/'?'homepage':p.path==='/404/'?'not-found':p.path==='/services-2/'?'service-hub':p.city?'area-guide':p.service||p.path==='/services/lawn-maintenance/'?'service':p.component?'package-component-guide':p.path==='/getestimate/'?'conversion':p.path==='/reviews/'?'testimonials':'company',parent:p.city?'/service-areas/':p.path.startsWith('/services/')?'/services-2/':'/',schema:p.path==='/404/'?[]:['Organization','WebSite','WebPage',...(p.path!=='/'?['BreadcrumbList']:[]),...(p.service||p.path==='/services/lawn-maintenance/'?['Service']:[])],cta:'/getestimate/',releaseDisposition:'local-review-only; fact and Page Map approval required'})),redirects:{'/services/':'/services-2/','/about/':'/our-mission/','/gallery/':'/projects/','/contact/':'/getestimate/'},externalPreserved:['/franchising/','/privacy-policy/','/terms-conditions/','/meet-the-founders/','/watch-yardu-video/'],heldRoutes:['/join-the-movement/'],notes:'Local Page Map candidate only; no redirects deployed. Four components have supporting guides, labelled parts of the published package rather than independent bookings. Six distinct area guides are review candidates. Raleigh/Cary have deeper context. Additional service groups verified on public homepage October 1; detailed capacity, project proof, and neighborhood-level coverage require client facts. Jotform deliberately not embedded. sitemap.xml empty while noindex; sitemap-candidate.xml documents potential release URLs.'},null,2));
console.log(`Built ${pages.length} local pages in dist. Lead submission and indexing disabled.`);
