import nodeProcess from 'node:process';
import {mkdir, writeFile, cp, rm, readFile} from 'node:fs/promises';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {icons} from './icons.mjs';
import {areaHub, areaLinks, localGuides} from './local-content.mjs';
import {breadcrumbHTML, structuredData} from './seo.mjs';
import {componentGuides, componentLinks} from './component-content.mjs';
import {secondaryAreas} from './secondary-areas.mjs';
import {richCoverage, richReviews} from './rich-components.mjs';
import {additionalServices} from './additional-services.mjs';
import {chatMarkup} from './chat-markup.mjs';
import {googleProfile} from './google-profile.mjs';
import {shareMetadata,resolveShareOrigin} from './share-metadata.mjs';
import {referenceLayout} from './reference-layout.mjs';
const production=nodeProcess.argv.includes('--production')||nodeProcess.env.VERCEL_ENV==='production';
const shareOrigin=production?'https://hireyardu.com':resolveShareOrigin();
const root = dirname(dirname(fileURLToPath(import.meta.url)));
const imageDimensions=JSON.parse(await readFile(join(root,'asset-dimensions.json'),'utf8'));
const correctImageDimensions=(html)=>html.replace(/<img\b[^>]+>/g,tag=>{const name=tag.match(/src="\/assets\/images\/([^\"]+)"/)?.[1];const image=imageDimensions[name];const variants=Object.values(responsiveImages).find(item=>item.default===name)?.variants;const srcset=variants?.map(v=>`/assets/images/${v.name} ${v.width}w`).join(', ');if(srcset){tag=tag.replace(/\s(?:srcset|sizes)="[^"]*"/g,'');tag=tag.replace('>',` srcset="${srcset}" sizes="${(tag.includes('home-hero-image')||tag.includes('inner-hero-image'))?'100vw':'(max-width: 760px) 100vw, 50vw'}">`);}if(image)tag=tag.replace(/width="\d+"/,`width="${image.width}"`).replace(/height="\d+"/,`height="${image.height}"`);if(variants){const avif=variants.map(v=>`/assets/images/${v.avif} ${v.width}w`).join(", ");const sizes=tag.match(/sizes="([^\"]+)"/)?.[1]||"100vw";const source=`<source type="image/avif" srcset="${avif}" sizes="${sizes}">`;return tag.includes("hero-image")?source+tag:`<picture class="responsive-picture">${source}${tag}</picture>`;}return tag;});
const origin='https://hireyardu.com';
const phone='(919) 592-8328';
const towns=['Raleigh','Cary','Apex','Wake Forest','Fuquay-Varina','Holly Springs'];
const responsiveImages=JSON.parse(await readFile(join(root,'responsive-images.json'),'utf8'));
const img=(name)=>`/assets/images/${name==='yardu-logo.svg'?'yardu-logo-centered.svg':responsiveImages[name]?.default||name}`;
const links=[['/','Home'],['/services-2/','Services'],['/our-mission/','Mission'],['/projects/','Projects'],['/reviews/','Reviews'],['/service-areas/','Service Area']];
const serviceNav=[{slug:'lawn-maintenance',name:'The YardU Special',short:'The complete core lawn care package.'},...componentGuides.map(g=>({slug:g.slug,name:g.name,short:'Part of the YardU Special.'})),...additionalServices.map(g=>({...g,name:g.nav}))];
const serviceMenu=(mobile=false)=>`<details class="${mobile?'':'nav-dropdown service-disclosure'}"><summary>Services <span aria-hidden="true">${mobile?'+':'⌄'}</span></summary><div class="${mobile?'':'services-menu'}"><a href="/services-2/"><span>All services</span><small>Find the right scope for your property.</small></a>${serviceNav.map(g=>`<a href="/services/${g.slug}/"><span>${g.name}</span><small>${g.short}</small></a>`).join('')}</div></details>`;
const nav=(path,mobile=false)=>links.map(([href,label])=>href==='/services-2/'?serviceMenu(mobile):`<a href="${href}"${href===path?' aria-current="page"':''}>${label}</a>`).join('');
const estimate=(label='Request a free estimate')=>`<a class="button button-primary" href="/getestimate/"><span>${label}</span><span class="button-icon">${icons.arrow}</span></a>`;
const call=()=>`<a class="button button-outline-dark" href="tel:+19195928328"><span>Call ${phone}</span>${icons.phone}</a>`;
const heading=(eyebrow,title,copy='')=>`<div class="section-heading"><p class="eyebrow">${eyebrow}</p><h2>${title}</h2>${copy?`<p>${copy}</p>`:''}</div>`;
const presentation=referenceLayout({img,icons,estimate,call,heading,additionalServices,googleProfile});
const header=(path)=>`<a class="skip-link" href="#main-content">Skip to content</a><div class="topbar" role="complementary" aria-label="YardU contact information"><div class="shell topbar-inner"><div class="utility-local"><span>${icons.pin}Raleigh &amp; the Triangle, NC</span><span>${icons.clock}Contact hours: 7 AM–7 PM every day</span></div><nav aria-label="Utility navigation"><a href="/projects/">Gallery</a><a href="${googleProfile.googleReviewsUrl}" target="_blank" rel="noopener">Google reviews</a><a class="utility-contact" href="/getestimate/">Contact</a></nav></div></div><div class="header-sentinel"></div><header class="site-header" data-site-header><div class="shell nav-shell"><a class="brand" href="/" aria-label="YardU home"><img src="${img('yardu-logo.svg')}" alt="YardU — Landscaping with a Purpose" width="500" height="500"></a><nav class="desktop-nav" aria-label="Primary navigation">${nav(path)}</nav><div class="nav-actions">${estimate('Request estimate')}<button class="menu-toggle" type="button" aria-label="Open menu" aria-expanded="false" aria-controls="mobile-menu">${icons.menu}</button></div></div></header><div class="menu-scrim" data-menu-scrim hidden></div><aside class="mobile-menu" id="mobile-menu" aria-label="Mobile navigation" hidden><div class="mobile-menu-top"><img src="${img('yardu-logo.svg')}" alt="YardU" width="90" height="90"><button class="menu-close" aria-label="Close menu">${icons.close}</button></div><div class="mobile-menu-actions">${estimate()}${call()}</div><nav aria-label="Mobile navigation links">${nav(path,true)}</nav><p>Landscaping with a Purpose</p></aside>`;
const footer=()=>`<footer class="site-footer"><div class="shell footer-grid"><div class="footer-brand"><img src="${img('yardu-logo.svg')}" alt="YardU" width="500" height="500"><p>Training tomorrow’s youth, one yard at a time.</p><a class="text-link" href="https://www.instagram.com/theyarduniversity/" target="_blank" rel="noopener">${icons.instagram} Follow YardU</a></div><div><h2>Services</h2><ul><li><a href="/services/lawn-maintenance/">The YardU Special</a></li>${additionalServices.map(g=>`<li><a href="/services/${g.slug}/">${g.nav}</a></li>`).join('')}<li><a href="/services-2/">All services</a></li><li><a href="/getestimate/">Request an estimate</a></li></ul></div><div><h2>Company</h2><ul>${links.slice(2).map(([href,l])=>`<li><a href="${href}">${l}</a></li>`).join('')}<li><a href="/meet-the-founders/">Meet Jackson</a></li></ul></div><div><h2>Contact</h2><ul><li><a href="tel:+19195928328">${phone}</a></li><li>Serving Raleigh, Cary, Apex, Wake Forest, Fuquay-Varina &amp; Holly Springs, NC. Confirm your property and service availability with YardU.</li><li>Contact hours: 7 AM–7 PM every day</li><li><a href="sms:+19195928328">Text ${phone}</a></li><li><a href="mailto:jackson@hireyardu.com">jackson@hireyardu.com</a></li><li><a href="https://www.linkedin.com/company/yardu">LinkedIn</a></li></ul></div></div><div class="shell footer-bottom"><p>© 2026 YardU. All rights reserved.</p><div><a href="/sitemap.xml">Sitemap</a></div></div></footer>`;
const parts=[['Mowing','mowing.png','Grass cut to suit your turf, with an even finish.','Striped lawn pictured on YardU’s current website'],['Edging','edging.png','Clean lines along sidewalks, driveways, and landscape beds.','Defined landscape bed pictured on YardU’s current website'],['Trimming','trimming-preview.jpg','Grass and weeds around fences, obstacles, and hard-to-reach corners.','YardU crew member trimming grass'],['Blowing off surfaces','property-lawn-preview.jpg','Grass clippings and debris cleared from the finished surfaces.','Lawn pictured on YardU’s current website']];
const cards=()=>`<div class="service-grid home-service-grid">${parts.map(([title,image,copy,alt],i)=>`<a class="service-card" href="/services/${['mowing','edging','trimming','blowing'][i]}/"><img src="${img(image)}" alt="${alt}" width="900" height="1100" loading="lazy"><div class="service-card-shade"></div><div class="service-card-copy"><span>0${i+1}</span><h3>${title}</h3><span class="service-card-accent" aria-hidden="true"></span><p>${copy}</p><span class="service-card-link">Included in the YardU Special ${icons.arrow}</span></div></a>`).join('')}</div>`;
const intro=()=>presentation.intro();
const services=()=>presentation.services();
const process=()=>`<section class="process section-pad"><div class="shell process-grid"><div class="process-visual"><img src="${img('trimming-preview.jpg')}" alt="YardU lawn care in progress" width="1200" height="900" loading="lazy"><div class="process-caption"><span>Start with your yard.</span><strong>Make room for your life.</strong></div></div><div class="process-copy">${heading('A clear starting point','Let’s talk about your yard.','A few details help YardU understand what you need.')}<div class="accordion process-accordion" data-accordion>${[['Tell us about the property','Share the location, lawn condition, access, and the areas you would like cared for.'],['Discuss the right scope','Ask about the core package and describe any additional work so the team can confirm what is available.'],['Confirm your estimate','Discuss price, timing, and service details directly with YardU before booking.'],['Agree on the finishing details','Confirm the areas and finished surfaces to include, and anything that needs a separate scope.']].map(([t,c],i)=>`<details${i===0?' open':''}><summary><span>0${i+1}</span><strong>${t}</strong>${icons.plus}</summary><div><p>${c}</p></div></details>`).join('')}</div></div></div></section>`;
const coverage=()=>richCoverage(estimate);
const testimonials=()=>richReviews();
const galleryImages=[['client-striped-lawn.webp','Striped lawn and mower in a photo provided by YardU'],['client-rock-bed.webp','Japanese maple and finished rock bed in a photo provided by YardU'],['client-crew-customer.webp','YardU crew members with a customer'],['client-backyard.webp','Backyard lawn and shrubs in a photo provided by YardU'],['client-leaf-cleanup.webp','Collected leaves pictured by YardU'],['client-truck.webp','YardU-branded truck']];
const gallery=()=>`<section class="gallery-preview section-pad"><div class="shell gallery-heading-row">${heading('The YardU view','The details show in the finish.','A closer look at lawns, landscape beds, and outdoor spaces.')}<a class="text-link text-link-light" href="/projects/">View the full gallery ${icons.arrow}</a></div><div class="gallery-collage shell">${galleryImages.map(([src,alt],i)=>`<figure class="gallery-item gallery-item-${i+1}"><img src="${img(src)}" alt="${alt}" loading="lazy" width="1000" height="1200"></figure>`).join('')}</div></section>`;
const additionalSection=()=>`<section class="services section-pad additional-services"><div class="shell">${heading('Beyond the core package','More ways to care for your property.','Refresh your landscape beds, clear accumulated leaves, shape an outdoor space, refresh a lawn with sod, or arrange a property cleanup.')}<div class="service-grid">${additionalServices.map((g,i)=>`<a class="service-card" href="/services/${g.slug}/"><img src="${img(g.image)}" alt="${g.image==='property-lawn-preview.jpg'?'Residential lawn pictured on YardU’s website':g.image==='backyard.jpeg'?'Backyard pictured on YardU’s website':g.name+' imagery published by YardU'}" width="900" height="1100" loading="lazy"><div class="service-card-shade"></div><div class="service-card-copy"><span>0${i+1}</span><h3>${g.nav}</h3><span class="service-card-accent" aria-hidden="true"></span><p>${g.short}</p><span class="service-card-link">Explore the service ${icons.arrow}</span></div></a>`).join('')}</div></div></section>`;
const faqs=[['What is included in the YardU Special?','The core package includes mowing, edging, weed whacking and trimming, and blowing off surfaces. YardU’s published service description also includes light shaping of low hedges and shrubs as part of the regular mowing cycle. Confirm your property’s scope with the team.'],['Where does YardU work?',`YardU serves ${towns.slice(0,-1).join(', ')}, and ${towns.at(-1)}, North Carolina. Confirm your property, requested service, and current availability with the team.`],['What does “Landscaping with a Purpose” mean?','YardU creates opportunities for young people to learn work ethic, communication, professionalism, and responsibility through real work.'],['How do I request an estimate?',`Call ${phone} to discuss your property. The form in this local preview demonstrates the request flow; it does not send a lead.`]];
const faq=(service)=>`<section class="faq-section section-pad"><div class="shell faq-grid"><div>${heading('Straight answers','Questions before you book?','Start with the details that matter to your property.')}<a class="text-link" href="/getestimate/">Talk to YardU ${icons.arrow}</a></div><div class="accordion faq-accordion" data-accordion>${(service?[[`How do I discuss ${service.name.toLowerCase()} with YardU?`,service.intro+" Share the property location, current condition, access, and your goals so YardU can confirm the actual scope."],["What should I confirm before booking?","Agree on the included areas and work, any materials or preparation, estimate, availability, and schedule directly with YardU."],["How do I contact YardU?",`Call or text ${phone}, or email jackson@hireyardu.com. Contact hours are 7 AM–7 PM every day.`]]:faqs).map(([q,a],i)=>`<details${i===0?' open':''}><summary><strong>${q}</strong>${icons.plus}</summary><div><p>${a}</p></div></details>`).join('')}</div></div></section>`;
const form=()=>`<section class="contact-section section-pad" id="estimate"><div class="shell contact-grid"><div class="contact-copy"><p class="eyebrow eyebrow-light">Start with your property</p><h2>Your lawn.<br>Our purpose.</h2><p>Tell YardU what your lawn needs. A conversation is the first step toward the right scope and estimate.</p><div class="contact-direct"><a class="contact-phone" href="tel:+19195928328"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M7.5 3.8 10 8l-2.2 2.2c1.4 2.8 3.2 4.6 6 6l2.2-2.2 4.2 2.5-.7 3.2c-.2.8-.9 1.3-1.7 1.3C9.6 20.6 3.4 14.4 3 6.2c0-.8.5-1.5 1.3-1.7l3.2-.7Z"/></svg><span><small>Call or text · 7 AM–7 PM every day</small><strong>(919) 592-8328</strong></span></a><a href="sms:+19195928328">Text YardU →</a><a href="mailto:jackson@hireyardu.com">jackson@hireyardu.com</a></div><p class="preview-note">Send your request securely through YardU’s Homeworks form. Preferred dates are requests; the team will confirm availability.</p></div><div class="yardu-form-card"><p class="eyebrow">Request an estimate</p><h3>Tell us about your yard.</h3><iframe id="homeworks-request-form" title="YardU estimate request form" src="https://secure.copilotcrm.com/client/guest/requests/embedNew/93604580-7d65-4275-8638-95088dcb20c6" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" style="width:100%;height:1900px;border:0;background:#fff"></iframe><p class="homeworks-fallback">Form not loading? <a href="https://secure.copilotcrm.com/client/guest/requests/embedNew/93604580-7d65-4275-8638-95088dcb20c6" target="_blank" rel="noopener">Open the secure request form</a> or <a href="tel:+19195928328">call YardU</a>.</p></div></div></section>`;
const trust=()=>presentation.trust();
const homeHero=()=>presentation.homeHero();
const inner=(eyebrow,title,copy,image='property-lawn-preview.jpg',imageAlt='Landscape pictured on YardU’s website')=>`<section class="inner-hero"><picture class="inner-hero-visual"><img class="inner-hero-image" src="${img(image)}" width="1200" height="1600" alt="${imageAlt}" loading="eager" fetchpriority="high" decoding="async"></picture><div class="shell inner-hero-content"><p class="eyebrow eyebrow-light">${eyebrow}</p><h1>${title}</h1><p>${copy}</p><div class="button-row">${estimate()}${call()}</div></div></section>`;
const cta=()=>`<section class="simple-cta section-pad"><div class="shell simple-cta-inner"><div><p class="eyebrow eyebrow-light">Your yard is next</p><h2>Care for your lawn.<br>Invest in tomorrow.</h2></div>${estimate()}</div></section>`;
const pages=[
{path:'/',title:'Lawn Care in Raleigh & the Triangle | YardU',description:'YardU’s core lawn care package includes mowing, edging, trimming, and blowing off surfaces. Serving Raleigh, Cary, and neighboring NC communities.',body:homeHero()+trust()+intro()+services()+process()+presentation.why()+testimonials()+presentation.conversion()+gallery()+coverage()+faq()+form(),class:'home-page'},
{path:'/services-2/',title:'Lawn & Landscaping Services | YardU',description:'Explore YardU’s lawn package, landscaping, plant installs, aeration and overseeding, drainage, Christmas light installs, and snow removal.',body:inner('Our services','Lawn &amp; landscaping<br>services in Raleigh.','Explore the core lawn package and additional property services.')+trust()+services()+`<section class="section-pad"><div class="shell">${heading("Inside the YardU Special","Four connected lawn care details.","Explore the four components of the core lawn package.")}${cards()}</div></section>`+process()+faq()+cta()},
{path:'/services/lawn-maintenance/',title:'The YardU Special Lawn Mowing Package | YardU',description:'Four lawn care details in one core package: mowing, edging, trimming, and blowing off surfaces. Discuss your property with YardU.',body:inner('Lawn mowing & maintenance','Lawn mowing &amp;<br>maintenance in Raleigh.','Meet the four parts of the YardU Special.')+trust()+presentation.projectStrip()+`<section class="section-pad"><div class="shell">${heading('What’s included','From the first cut to the final cleanup.')}<div class="yardu-service-details">${parts.map(([t,i,c,a],n)=>`<article id="${['mowing','edging','trimming','blowing'][n]}"><img src="${img(i)}" alt="${a}" loading="lazy" width="900" height="900"><div><p class="eyebrow">0${n+1} · The YardU Special</p><h2>${t}</h2><p>${c}</p><a class="text-link" href="/services/${['mowing','edging','trimming','blowing'][n]}/">Explore this component →</a>${n===2?'<p>YardU’s published package includes light shaping of low hedges and shrubs as part of the regular mowing cycle. Discuss the scope for your property.</p>':''}</div></article>`).join('')}</div></div></section>`+`<section class="section-pad"><div class="shell local-content"><h2>Lawn care for your community</h2><p>Discuss your address and property needs with YardU. Read the local guides for useful preparation questions and resources.</p>${areaLinks}<p>YardU also lists Apex, Wake Forest, Fuquay-Varina, and Holly Springs. Use the <a href="/service-areas/">service area hub</a> to confirm your property's fit.</p><h2>Agree on the scope before booking</h2><p>Share the grass condition, access, fenced sections, edges, and surfaces to clear. Confirm the visit frequency, timing, and price directly with YardU. Work outside this package should be discussed separately.</p></div></section>`+process()+faq()+cta()},
{path:'/our-mission/',title:'Our Mission | YardU Landscaping with a Purpose',description:'YardU gives young people opportunities to develop work ethic, communication, professionalism, and responsibility through lawn care.',body:inner('Our mission','A yard today.<br>A future tomorrow.','Training tomorrow’s youth, one yard at a time.','client-truck.webp')+intro()+`<section class="section-pad"><div class="shell mission-story">${heading('Built from experience','Work ethic is learned by doing.')}<p>Founder Jackson DeSilva, MBA, is an <a href="https://gopack.com/sports/football/roster/jackson-desilva/12421" target="_blank" rel="noopener">NC State football alum</a>. He brings lessons in hard work, discipline, and resilience to YardU’s purpose: giving young people a place to work, learn, and prepare for the future.</p><blockquote>“It’s more than just lawn care. It’s about building a workforce, teaching responsibility, and shaping the leaders of tomorrow.”<cite>YardU’s mission</cite></blockquote><p>Each yard is an opportunity to practice responsibility, communication, and professionalism. Your lawn care becomes part of something bigger.</p></div></section>`+testimonials()+cta()},
{path:'/meet-the-founders/',title:'Meet Jackson DeSilva | YardU Founder',description:'Meet YardU Founder Jackson DeSilva, MBA, an NC State football alum bringing real work and purpose to lawn care and landscaping.',body:inner('YardU Founder','Meet Jackson<br>DeSilva.','Founder · MBA · NC State Football Alum','client-truck.webp')+`<section class="section-pad"><div class="shell mission-story">${heading('Landscaping with a Purpose','Real work. Lasting lessons.')}<p>Jackson DeSilva is YardU’s Founder. An <a href="https://gopack.com/sports/football/roster/jackson-desilva/12421" target="_blank" rel="noopener">NC State football alum</a> with an MBA, Jackson brings a purpose to lawn care and landscaping: helping young people build work ethic, responsibility, communication, and professionalism through real work.</p><p>Explore Jackson’s official <a href="https://gopack.com/sports/football/roster/jackson-desilva/12421" target="_blank" rel="noopener">2023 NC State football profile</a> and <a href="https://gopack.com/sports/football/roster/jackson-desilva/11334" target="_blank" rel="noopener">2022 player bio</a>.</p><h2>Purpose in every yard</h2><p>Each property is an opportunity to care for an outdoor space and practice skills that matter beyond it. Learn more about <a href="/our-mission/">YardU’s mission</a> and explore <a href="/services-2/">the lawn care and landscaping services</a>.</p><h2>Talk with YardU</h2><p>Call or text <a href="tel:+19195928328">(919) 592-8328</a>, or email <a href="mailto:jackson@hireyardu.com">jackson@hireyardu.com</a>. Contact hours are 7 AM–7 PM every day. Confirm your property, scope, and current availability with the team.</p></div></section>`+cta()},
{path:'/projects/',title:'Lawn Care Gallery | YardU',description:'Explore lawn care, landscape beds, and outdoor-space imagery from YardU.',body:inner('The YardU view','The details make<br>the difference.','Explore lawns, landscape beds, and outdoor spaces from YardU.')+gallery()+cta()},
{path:'/service-areas/',title:'Service Areas | YardU in Raleigh, Cary & Nearby Communities',description:'YardU lists Raleigh, Cary, Apex, Wake Forest, Fuquay-Varina, and Holly Springs, NC. Confirm your exact property and availability with the team.',body:inner('North Carolina communities','Close to home.<br>Built on purpose.','Find your community and discuss your property with YardU.')+coverage()+areaHub+faq()+cta()},
{path:'/getestimate/',title:'Request an Estimate | YardU',description:'Discuss your lawn care needs with YardU at (919) 592-8328. Send your property and service details securely to YardU through Homeworks.',body:inner('Let’s start with your yard','Tell us what<br>you have in mind.','A clear scope starts with a conversation.')+form()+process()},
{path:'/404/',title:'Page Not Found | YardU',description:'Find your way back to YardU lawn care.',body:inner('404','Let’s get back<br>to your yard.','This page could not be found.')+`<section class="section-pad"><div class="shell"><a class="button button-primary" href="/">Back to home ${icons.arrow}</a></div></section>`}
];
for(const guide of [...localGuides,...secondaryAreas])pages.push({...guide,body:inner(`${guide.city}, North Carolina`,`${guide.city==='Wake Forest'?'Landscaping':'Lawn care'} in<br>${guide.city}.`,guide.intro,'client-truck.webp')+trust()+`<section class="section-pad area-guide-copy"><div class="shell local-content">${guide.content}<h2>Explore services for your property</h2><p><a href="/services/lawn-maintenance/">The YardU Special</a> brings its four core components together. Confirm your property, service scope, and scheduling availability directly with YardU.</p>${componentLinks()}<h2>Property services in ${guide.city}</h2><p>Explore ${additionalServices.map(g=>`<a href="/services/${g.slug}/">${g.nav}</a>`).join(', ')}. Discuss the property, separate scope, and current availability with the team.</p>${areaLinks}</div></section>`+services()+process()+faq()+cta()});
for(const guide of componentGuides)pages.push({path:`/services/${guide.slug}/`,title:`${guide.name} | Part of the YardU Special Lawn Package`,description:guide.intro+' Explore scope, property questions, and the other parts of the package.',component:guide.name,body:inner('Part of the YardU Special',guide.name+'<br>in Raleigh &amp; the Triangle.',guide.intro,guide.image)+trust()+presentation.projectStrip()+`<section class="section-pad service-scope"><div class="shell local-content">${presentation.scopeContent(guide.content)}<h2>One package, four connected details</h2><p>Return to <a href="/services/lawn-maintenance/">the complete YardU Special</a> or explore the other components.</p>${componentLinks(guide.slug)}<h2>Find your area</h2><p>Use the local guides to prepare your property request and confirm address-level availability.</p>${areaLinks}</div></section>`+presentation.serviceProcess({...guide,nav:guide.name})+faq(guide)+cta()});
pages.push({path:'/reviews/',title:'YardU Testimonials | Landscaping with a Purpose',description:'Read customer and community testimonials shared by YardU.',body:inner('YardU stories','Purpose people<br>can get behind.','The mission means more when you hear from the community.')+testimonials()+cta()});
for(const g of additionalServices)pages.push({path:`/services/${g.slug}/`,title:`${g.name} in Raleigh & the Triangle | YardU`,description:`${g.name} from YardU in Raleigh and the Triangle, NC. ${g.short} Confirm your property, scope, and availability with the team.`,component:g.name,service:true,body:inner('YardU additional services',g.name+'<br>in Raleigh &amp; the Triangle.',g.intro,g.image,g.imageAlt)+trust()+presentation.projectStrip()+`<section class="section-pad service-scope"><div class="shell local-content">${presentation.scopeContent(g.content)}<h2>Explore related work</h2><p>Compare the <a href="/services-2/">complete service hub</a> and <a href="/services/lawn-maintenance/">the core lawn package</a>.</p><div class="coverage-links">${additionalServices.filter(other=>other.slug!==g.slug).map(other=>`<a href="/services/${other.slug}/">${other.nav}</a>`).join('')}</div><h2>Your community</h2>${areaLinks}</div></section>`+presentation.serviceProcess(g)+faq(g)+cta()});
const shell=(p)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#000000"><title>${p.title.replaceAll('&','&amp;')}</title><meta name="description" content="${p.description.replaceAll('&','&amp;')}"><meta name="robots" content="${production&&p.path!=='/404/'?'index,follow':'noindex,nofollow'}"><link rel="canonical" href="${origin}${p.path}"><link rel="icon" href="${img('yardu-logo.svg')}" type="image/svg+xml">${shareMetadata(p,shareOrigin)}<link rel="preload" href="/assets/fonts/poppins-latin-400.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/assets/fonts/poppins-latin-700.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/fonts.css"><link rel="stylesheet" href="/assets/poppins.css"><link rel="stylesheet" href="/assets/template.css"><link rel="stylesheet" href="/assets/yardu.css"><link rel="stylesheet" href="/assets/yardu-chat.css"><link rel="stylesheet" href="/assets/reference-layout.css"><meta property="og:type" content="website"><meta property="og:site_name" content="YardU">${p.path==='/404/'?'':structuredData(p)}<script src="/assets/site.js" defer></script><script src="/assets/yardu-chat.js" type="module"></script><script type="module" src="/assets/area-map.js"></script></head><body class="${p.class||'inner-page'}">${header(p.path)}<main id="main-content">${p.body.startsWith('<section class="inner-hero"')?p.body.replace('</section>',`</section>${breadcrumbHTML(p)}`):p.body}</main>${footer()}${chatMarkup()}<div class="mobile-cta-bar" role="navigation" aria-label="Quick contact"><a href="tel:+19195928328">${icons.phone}Call YardU</a><a href="/getestimate/">Request estimate ${icons.arrow}</a></div></body></html>`;
const dist=join(root,'dist');await rm(dist,{recursive:true,force:true});await mkdir(dist,{recursive:true});await cp(join(root,'assets'),join(dist,'assets'),{recursive:true});
for(const file of ['template.css','yardu.css','yardu-chat.css','reference-layout.css']){const path=join(dist,'assets',file);const css=await readFile(path,'utf8');await writeFile(path,css.replace(/\/\*[\s\S]*?\*\//g,'').replace(/\n[ \t]*/g,' ').replace(/[ \t]{2,}/g,' ').trim());}
for(const p of pages){const file=p.path==='/'?'index.html':p.path==='/404/'?'404.html':`${p.path.slice(1)}index.html`;await mkdir(dirname(join(dist,file)),{recursive:true});await writeFile(join(dist,file),correctImageDimensions(shell(p)));}
await writeFile(join(dist,'sitemap-candidate.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.filter(p=>p.path!='/404/').map(p=>`<url><loc>${origin}${p.path}</loc></url>`).join('')}</urlset>`);
await writeFile(join(dist,'sitemap.xml'),production?await readFile(join(dist,'sitemap-candidate.xml'),'utf8'):'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>');
await writeFile(join(dist,'robots.txt'),production?'User-agent: *\nAllow: /\nSitemap: https://hireyardu.com/sitemap.xml\n':'User-agent: *\nDisallow: /\n');
await writeFile(join(root,'route-manifest.json'),JSON.stringify({mode:production?'production':'local-review-only',origin,routes:pages.map(p=>({path:p.path,title:p.title,description:p.description,canonical:origin+p.path,indexable:production&&p.path!=='/404/',type:p.path==='/'?'homepage':p.path==='/404/'?'not-found':p.path==='/services-2/'?'service-hub':p.city?'area-guide':p.service||p.path==='/services/lawn-maintenance/'?'service':p.component?'package-component-guide':p.path==='/getestimate/'?'conversion':p.path==='/reviews/'?'testimonials':'company',parent:p.city?'/service-areas/':p.path.startsWith('/services/')?'/services-2/':'/',schema:p.path==='/404/'?[]:['Organization','WebSite','WebPage',...(p.path!=='/'?['BreadcrumbList']:[]),...(p.service||p.path==='/services/lawn-maintenance/'?['Service']:[])],cta:'/getestimate/',releaseDisposition:'local-review-only; fact and Page Map approval required'})),redirects:{'/services/':'/services-2/','/about/':'/our-mission/','/gallery/':'/projects/','/contact/':'/getestimate/'},externalPreserved:['/franchising/','/privacy-policy/','/terms-conditions/','/watch-yardu-video/'],heldRoutes:['/join-the-movement/'],notes:'Local Page Map candidate only; no redirects deployed. Four components have supporting guides, labelled parts of the published package rather than independent bookings. Six distinct area guides are review candidates. Raleigh/Cary have deeper context. Additional service groups verified on public homepage October 1; detailed capacity, project proof, and neighborhood-level coverage require client facts. Jotform deliberately not embedded. sitemap.xml empty while noindex; sitemap-candidate.xml documents potential release URLs.'},null,2));
console.log(`Built ${pages.length} pages in ${production?'production':'local preview'} mode.`);
