import {chromium,browserPath,requireBrowserQA} from './browser-runtime.mjs';
import {mkdir,writeFile} from 'node:fs/promises';import {resolve} from 'node:path';import assert from 'node:assert/strict';
requireBrowserQA();const root=resolve(import.meta.dirname,'..'),evidence=resolve(root,'../evidence');await mkdir(evidence,{recursive:true});const b=await chromium.launch({executablePath:browserPath});const results=[],errors=[],requests=[];
try{
 for(const [width,height] of [[320,664],[360,740],[390,664],[390,759],[390,844],[500,844],[768,1024],[844,390]]){
  const p=await b.newPage({viewport:{width,height},isMobile:true,hasTouch:true});p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(!['GET','HEAD'].includes(r.method()))requests.push(r.url());});
  await p.goto('http://localhost:4319/',{waitUntil:'networkidle'});await p.evaluate(()=>document.fonts.ready);
  const get=()=>p.evaluate(()=>{const rect=s=>{const r=document.querySelector(s).getBoundingClientRect();return {top:r.top,bottom:r.bottom,left:r.left,right:r.right,width:r.width,height:r.height};};return {width:innerWidth,height:innerHeight,header:rect('.site-header'),bar:rect('.mobile-cta-bar'),image:rect('.home-hero-visual'),content:rect('.home-hero-content'),overflow:document.documentElement.scrollWidth>innerWidth,imageStyle:getComputedStyle(document.querySelector('.home-hero-image')).objectFit,barStyle:getComputedStyle(document.querySelector('.mobile-cta-bar')).borderRadius};});
  let s=await get();assert.equal(s.overflow,false);assert.equal(s.header.top,0);assert.ok(Math.abs(s.bar.bottom-s.height)<1);assert.equal(s.bar.left,0);assert.equal(s.bar.right,s.width);assert.equal(s.barStyle,'0px');assert.equal(s.imageStyle,'cover');assert.ok(s.content.top>=s.image.bottom-1);assert.ok(Math.abs(s.image.width/s.image.height-1.6)<.01);
  await p.evaluate(()=>scrollTo(0,550));s=await get();assert.equal(s.header.top,0);assert.ok(Math.abs(s.bar.bottom-s.height)<1);
  await p.evaluate(()=>{const r=document.documentElement;r.style.setProperty('--safe-top','20px');r.style.setProperty('--safe-bottom','34px');r.style.setProperty('--safe-left','18px');r.style.setProperty('--safe-right','18px');});s=await get();assert.equal(s.header.height,88);assert.equal(s.bar.height,87);
  const safe=await p.locator('.mobile-cta-bar').evaluate(e=>({bottom:getComputedStyle(e).paddingBottom,left:getComputedStyle(e).paddingLeft,right:getComputedStyle(e).paddingRight,children:[...e.children].map(x=>{const r=x.getBoundingClientRect();return {left:r.left,right:r.right,bottom:r.bottom};})}));assert.equal(safe.bottom,'34px');assert.equal(safe.left,'18px');assert.equal(safe.right,'18px');assert.ok(safe.children.every(x=>x.left>=18&&x.right<=width-18&&x.bottom<=height-34));
  await p.getByRole('button',{name:'Open menu',exact:true}).click();assert.equal(await p.locator('.mobile-cta-bar').isVisible(),false);const menu=await p.locator('.mobile-menu').boundingBox();assert.ok(menu.x>=0&&menu.x+menu.width<=width+.5);await p.getByRole('button',{name:'Close menu',exact:true}).click();assert.equal(await p.locator('.mobile-cta-bar').isVisible(),true);
  results.push({width,height,headerFlush:true,actionsFlush:true,imageBeforeCopy:true,safeAreasSimulated:true,drawerFits:true});await p.close();
 }
 const p=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await p.addInitScript(()=>{const vv=new EventTarget();Object.assign(vv,{height:844,width:390,offsetTop:0,offsetLeft:0,scale:1});Object.defineProperty(window,'visualViewport',{value:vv,configurable:true});});await p.goto('http://localhost:4319/',{waitUntil:'networkidle'});await p.locator('.yardu-chat-launcher').click();await p.locator('#yardu-chat-message').focus();await p.evaluate(()=>{window.visualViewport.height=544;window.visualViewport.dispatchEvent(new Event('resize'));});assert.equal(await p.locator('.mobile-cta-bar').isVisible(),false);assert.equal(await p.locator('.yardu-chat-launcher').isVisible(),false);const panel=await p.locator('.yardu-chat-panel').boundingBox();assert.ok(panel.y>=68&&panel.y+panel.height<=544+.5);assert.equal(await p.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--keyboard-inset').trim()),'300px');await p.evaluate(()=>{document.activeElement.blur();window.visualViewport.height=844;window.visualViewport.dispatchEvent(new Event('resize'));});await p.waitForTimeout(50);assert.equal(await p.locator('.mobile-cta-bar').isVisible(),true);await p.locator('.yardu-chat-close').press('Escape');results.push({keyboardVisualViewportSimulation:'passed',livePosts:0});await p.close();
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
 await writeFile(resolve(root,'qa/mobile-results.json'),JSON.stringify({status:'passed',runner:'Existing isolated Chromium; mobile touch contexts',results,errors,requests,limitations:'Viewport sizes model expanded/collapsed browser space. Safe-area CSS values and keyboard visualViewport are simulated. Native iOS Safari toolbar, actual device keyboard, and WebKit rendering have not been tested; no WebKit browser is installed.'},null,2)+'\n');console.log(JSON.stringify({status:'passed',states:results.length,requests}));
}finally{await b.close();}
