// Presentation adapted from the requested visual reference. All content and imagery are YardU's.
export function referenceLayout({img,icons,estimate,call,heading,additionalServices,googleProfile}) {
 const homeHero=()=>`<section class="home-hero home-hero-truck"><picture class="home-hero-visual"><img class="home-hero-image" src="${img('client-truck.webp')}" sizes="100vw" loading="eager" decoding="async" alt="YardU’s red, black, and white branded truck, photographed by Jackson" width="1200" height="1600" fetchpriority="high"></picture><div class="home-hero-shade"></div><div class="home-hero-brand"><img src="${img('yardu-logo.svg')}" alt="YardU" width="500" height="500"></div><div class="shell home-hero-content"><p class="eyebrow eyebrow-light">Landscaping with a Purpose</p><h1 class="liquid-title"><span>Lawn care &amp;</span><span>landscaping</span><span>in Raleigh</span><span>&amp; the Triangle.</span></h1><p class="hero-copy">Care for your outdoor space with YardU’s lawn care, landscaping, hardscaping, and more. Real work today. Life skills for tomorrow.</p><div class="hero-action-wrap"><div class="button-row">${estimate('Get a free estimate')}<a class="button button-ghost-light" href="tel:+19195928328" aria-label="Call YardU now at (919) 592-8328">Call now ${icons.phone}</a></div><a class="hero-google" href="${googleProfile.googleReviewsUrl}" target="_blank" rel="noopener">${icons.google}<span>Read our Google reviews</span>${icons.arrow}</a></div></div></section>`;
 const trust=()=>`<section class="trust-rail shell" aria-label="Why YardU">${[
  ['85+ reviews','5.0 on Google','See what customers say about YardU. Snapshot · Oct 1, 2026.',googleProfile.googleReviewsUrl,'Read Google reviews'],
  ['Get a quote','Start with your yard','Tell YardU what you need. Confirm the property, scope, and availability.','/getestimate/','Request a free estimate'],
  ['6 towns','North Carolina roots','Raleigh, Cary, Apex, Holly Springs, Fuquay-Varina, and Wake Forest.','/service-areas/','Service area'],
  ['Let’s talk','Your property. Your scope.','Discuss your yard, service needs, and current availability.','/getestimate/','Get an estimate']
 ].map(([display,title,copy,href,label],i)=>`<a class="trust-card${i<2?' trust-card-cta':''}" href="${href}"${i===0?' target="_blank" rel="noopener"':''}><strong class="trust-display">${display}</strong><h2>${title}</h2><p>${copy}</p><span class="text-link">${label} ${icons.arrow}</span></a>`).join('')}</section>`;
 const intro=()=>`<section class="intro section-pad"><div class="shell intro-grid"><div class="intro-copy">${heading('Landscaping with a Purpose','A better yard.<br>A brighter future.','Founded by Jackson DeSilva, an NC State football alum, YardU brings real work and purpose together. Lawn care becomes a place for young people to learn responsibility, communication, and professionalism.')}<div class="button-row">${estimate()}<a class="button button-outline-dark" href="tel:+19195928328" aria-label="Call YardU now at (919) 592-8328">Call now ${icons.phone}</a><a class="text-link" href="/our-mission/">Meet the mission ${icons.arrow}</a></div><a class="intro-phone" href="tel:+19195928328">${icons.phone}${'(919) 592-8328'}</a></div><div class="intro-visual"><div class="image-shell"><img src="${img('client-crew-customer.webp')}" alt="Two YardU crew members with a customer" width="1200" height="1600" loading="lazy"></div><div class="intro-badge"><strong>Real work.</strong><span>Lasting lessons.</span></div></div></div></section>`;
 const offers=[{slug:'lawn-maintenance',nav:'The YardU Special',image:'client-striped-lawn.webp',short:'Mowing, edging, trimming, and blowing off surfaces.'},...additionalServices];
 const services=()=>`<section class="services home-services additional-services section-pad" id="services"><div class="shell home-services-intro"><div class="home-services-copy"><p class="eyebrow eyebrow-light">Our lawn &amp; landscaping services</p><h2>Make more of<br>your outdoor space.</h2><span class="lime-rule" aria-hidden="true"></span><p>Explore the YardU Special, lawn and landscape work, and seasonal property services. Choose a service to explore the work and discuss your property.</p></div><div class="home-services-truck"><img src="${img('client-truck.webp')}" alt="YardU’s branded truck" width="1200" height="1600" loading="lazy"></div></div><div class="shell"><div class="service-grid home-service-grid">${offers.map((g,i)=>`<a class="service-card" href="/services/${g.slug}/"><img src="${img(g.image)}" alt="${g.slug==='lawn-maintenance'?'Striped lawn in a client-provided YardU photo':g.imageAlt||'YardU project imagery for '+g.nav}" width="900" height="1100" loading="lazy"><div class="service-card-shade"></div><div class="service-card-copy"><span>${String(i+1).padStart(2,'0')}</span><h3>${g.nav}</h3><span class="service-card-accent" aria-hidden="true"></span><p>${g.short}</p><span class="service-card-link">Explore the service ${icons.arrow}</span></div></a>`).join('')}</div><div class="service-quote-strip"><p>Start with your property.<br><strong>Let’s find the right scope.</strong></p>${estimate('Get a free estimate')}</div></div></section>`;
 const why=()=>`<section class="why section-pad"><div class="shell why-grid"><div>${heading('Why YardU','Care that goes<br>beyond the yard.')}<div class="why-benefits">${[
 ['Purpose in the work','Your property care helps young people practice work ethic and responsibility.'],
 ['A clear conversation','Discuss the property, included work, estimate, and schedule before booking.'],
 ['Rooted in the Triangle','Explore six local communities and confirm availability for your address.']
 ].map(([t,c],i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><div><h3>${t}</h3><p>${c}</p></div></article>`).join('')}</div></div><img src="${img('client-rock-bed.webp')}" alt="A Japanese maple and finished rock bed photographed by YardU" width="1200" height="1600" loading="lazy"></div></section>`;
 const conversion=()=>`<section class="conversion-banner section-pad"><div class="shell conversion-grid"><img src="${img('client-backyard.webp')}" alt="Backyard lawn and shrubs in a photo provided by YardU" width="1024" height="1024" loading="lazy"><div><p class="eyebrow eyebrow-light">Your yard is next</p><h2>Let’s make room<br>for something better.</h2><p>Tell YardU what you have in mind. A conversation starts your property plan.</p><div class="button-row">${estimate()}${call()}</div></div></div></section>`;
 const projectStrip=()=>`<section class="project-strip section-pad"><div class="shell">${heading('Project spotlights','Real yards. Real details.','Client-provided photos of YardU’s work and team.')}<div class="project-strip-grid">${[['yardu-striped-residential-lawn.webp','Mowing stripes across a residential lawn in YardU’s shared album'],['yardu-tiered-retaining-wall.webp','Tiered retaining wall and concrete steps in YardU’s shared album'],['yardu-backyard-paver-patio.webp','Curved paver patio in YardU’s shared album']].map(([src,alt])=>`<img src="${img(src)}" alt="${alt}" width="1200" height="1600" loading="lazy">`).join('')}</div><div class="center-row"><a class="button button-primary" href="/projects/">Our project gallery ${icons.arrow}</a></div></div></section>`;
 const scopeContent=html=>html.split(/(?=<h2>)/).filter(Boolean).map(block=>`<article class="scope-block">${block}</article>`).join('');
 const serviceProcess=g=>`<section class="service-process section-pad"><div class="shell">${heading('A clear starting point',`Planning your ${g.nav.toLowerCase()}.`)}<div class="service-process-steps">${[['Share the property',g.intro+' Share current conditions, goals, and access.'],['Confirm the included work','Discuss materials or methods where relevant, preparation, included areas, estimate, and timing with YardU.'],['Agree on the next step','Confirm the actual scope and schedule directly with the team before booking.']].map(([t,c],i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><h3>${t}</h3><p>${c}</p></article>`).join('')}</div></div></section>`;
 return {homeHero,trust,intro,services,why,conversion,projectStrip,scopeContent,serviceProcess};
}
